### ISSUE TITLE
A way to bind it to cx

### ISSUE THREAD

**Issue by sooheon** [Dewdrops/evil-exchange#6]
I'm used to this binding from tpope's package, but trying to replicate it here gives me an error that 'c' is a non-prefix key. Is there a way to reconcile this, or is it a fundamental limitation of emacs/evil?

**Comment by Dewdrops** [comment]
Due to the way how Emacs implements key bindings (via prefix keymap, not key sequence pressed in  certain milliseconds as Vim does), a key sequence can't be mapped if the first key of it has been mapped to another function/keymap. `c` has been mapped to `evil-change` in Evil, so can't be  remapped to `evil-exchange`. I choose `gx` because it's similar to `cx` (`x` means exchange, I guess), not conflicted with Evil or other popular evil plugins, and easy to implement.

However, using `cx` instead of `gx` is possible in Evil, the implementation maybe not trival but possible. If you'd like this key binding definitely, you can dive into the `evil-surround-edit` function in the excellent [evil-surround](https://github.com/timcharper/evil-surround) extension. This package implements `cs` as one of its default key bindings (by intercepting the dispatch process in evil operator state).

**Comment by noctuid** [comment]
@sooheon @Dewdrops 

> a key sequence can't be mapped if any prefix sequence of it has been mapped to another function

Well, this is also true of vim with `notimeout` (e.g. `co` mapping can't work if `cow` mapping exists).

Here is what I'm using (same method as evil-surround):
```
(defun noctuid/evil-exchange ()
  (interactive)
  (call-interactively #'evil-exchange)
  (setq evil-inhibit-operator t))

(define-key evil-operator-state-map "x" 'noctuid/evil-exchange)
```

If you only wanted to bind `cx`:
```
(defun noctuid/evil-exchange ()
  (interactive)
  (case evil-this-operator
    (evil-change (call-interactively #'evil-exchange))
    (evil-cp-change (call-interactively #'evil-exchange))
    ;; (evil-delete ...something-else)
	...
    (t ...))
  (setq evil-inhibit-operator t))
```
It might be nice to add this to the readme?

**Comment by Dewdrops** [comment]
@sooheon @noctuid 
Thanks for the feedbacks and advice. I've pushed some code into `vim-compatible` branch, please check that branch and help me test if the new bindings work.

To binding `evil-exchange` to `cx`:
```
(require 'evil-exchange)
(evil-exchange-cx-install)
```
The brand new `evil-exchange-cx-install` function will try to mimic the bindings of the original vim plugin, i.e., `cx` in normal state binds to `evil-exchange`, `cxc` in normal state binds to `evil-exchange-cancel`, and `X` in visual state binds to `evil-exchange`.

If this setting works, I'll merge the code to master later.

**Comment by sooheon** [comment]
I may have made a mistake in enabling it, but "cxiw" gives me "evil-motion-range: Can't find iw"

**Comment by Dewdrops** [comment]
```
emacs -Q
(require 'evil)
(require 'evil-exchange)
(evil-exchange-cx-install)
```
This works on my emacs (with latest evil from melpa, emacs 24.5.1 in Mac OSX).

**Comment by noctuid** [comment]
It's working fine for me (including cxiw). Thank you, I like the idea of having this as an option.

**Comment by Dewdrops** [comment]
@sooheon @noctuid

Thank you for the feedbacks. I've updated the master branch.
Because the new `evil-exchange-cx-install` function depends on evil's internal implementation of operator  state, it may break on old evil version or conflict with other plugins. Any feedbacks or PRs are welcome.

**Comment by CestDiego** [comment]
@Dewdrops Is that really an issue though? if there is a breaking change upstream and that breaks this package that doesn't mean it's experimental does it? Is this the only reason why this was labelled experimental?

**Comment by Dewdrops** [comment]
@CestDiego Yes, I agree that the implementation details shouldn't necessarily be an issue. I marked this feature as experimental mainly because I'm not sure the implementation is good/robust enough. Since there's no incompatibility reported till now, maybe it's time to remove the experimental label.

**Comment by sooheon** [comment]
May just want to document that many packages will want to override the `evil-change` under `c`, and in that case PRs welcome for compatibility. Also there is an incompatibility with evil-snipe, which uses the `x` binding under operator state, so I've had to unbind that. Those are the only issues i've come across.

**Comment by Dewdrops** [comment]
@sooheon
 
Thanks for your feedback and Suggestion. Documents have been updated.
